name: Gemini API Script Runner

on:
  push:
    branches:
      - main

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand({ ping: 1 })' | mongosh localhost:27017/test --quiet"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      GEMINI_API_KEY: ${{ secrets.MY_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: |
         echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV


      - name: Run Gemini script
        run: |
          python app/routes.py
