name: Gemini API Script Runner

on:
  push:
    branches:
      - main

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.MY_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flask flask_pymongo

      - name: Set PYTHONPATH
        run: |
         echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV


      - name: Run Gemini script
        run: |
          python app/routes.py
